services:
  backend:
    build: .
    container_name: sequra-backend
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_FILE_PATH=${DATABASE_FILE_PATH:-./data/sequraBackendDB.sqlite}
    command: >
      sh -c "npm ci &&
             if [ \"$NODE_ENV\" = \"development\" ]; then
               npm run dev;
             else
               npm run build && ${BACKEND_COMMAND:-node dist/common/infrastructure/server/index.js};
             fi"
    profiles:
      - production
      - test
      - development

  db:
    image: nouchka/sqlite3
    container_name: sequra-db
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    platform: linux/amd64

volumes:
  sqlite_data:
