version: '3.9'

services:
  backend:
    build: .
    container_name: sequra-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    command: sh -c "npm install && npm run build && node dist/server.js"
    environment:
      - NODE_ENV=development