version: "3.9"

services:
  backend:
    build: .
    container_name: sequra-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/src/data
    command: ["npx", "nodemon", "src/server.ts"]
    environment:
      - NODE_ENV=development

volumes:
  sqlite_data:
