services:
  backend:
    build: .
    container_name: sequra-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    depends_on:
      - db
    command: sh -c "npm ci && npm run build && node dist/server.js"

  db:
    image: nouchka/sqlite3
    container_name: sequra-db
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    platform: linux/amd64

volumes:
  sqlite_data:
